schoolmanagement - Copy/admissions/urls.py
from django.urls import path

from .views import *

from django.contrib.auth.decorators import login_required

urlpatterns = [

    path('register', register,name='register'),
    path('logout', logout,name='logout'),

     path('forgot-password/', ForgotPassword,name='forgot-password'),
     path('change-password/<token>/', ChangePassword,name='change-password'),


    path('newadm/', addadmission),
    path('delete/<int:id>', deletestudent),
    path('update/<int:id>', updatestudent),


    path('newfee/', addfee),
    path('delete-fee/<int:id>', deletefee),
    path('update-fee/<int:id>', updatefee),

    path('newteacher/', addteacher),
    path('delete-teacher/<int:id>', deleteteacher),
    path('update-teacher/<int:id>', updateteacher),

    path('id_generator/', id_generator),
    path('id_card/', id_card),
    path('detail/<int:id>/', detail , name="detail"), 
    path('delete-id_card/<int:id>', deleteid_card),

    path('contact/', Contact),

]

schoolmanagement - Copy/schoolmanagement/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from admissions import views
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('ad/', include('admissions.urls')),
    path('accounts/', include('django.contrib.auth.urls')),



]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

schoolmanagement - Copy/admissions/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User , on_delete=models.CASCADE)
    forgot_password_token = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


# Create your models here.
class Student(models.Model):
    name = models.CharField(max_length=1000 , verbose_name = "STUDENT FULL NAME" )
    fathername = models.CharField(max_length=1000 , verbose_name = "FATHER NAME")

    CLASSNAME_CHOICES =(
         ('Nursery' , 'Nursery'),
         ('L.K.G' , 'L.K.G'),
         ('U.K.G' , 'U.K.G'),
         ('1ˢᵗ' , '1ˢᵗ'),
         ('2ⁿᵈ' , '2ⁿᵈ'),
         ('3ʳᵈ' , '3ʳᵈ'),
         ('4ᵗʰ' , '4ᵗʰ'),
         ('5ᵗʰ' , '5ᵗʰ'),
         ('6ᵗʰ' , '6ᵗʰ'),
         ('7ᵗʰ' , '7ᵗʰ'),
         ('8ᵗʰ' , '8ᵗʰ'),
         ('9ᵗʰ' , '9ᵗʰ'),
         ('10ᵗʰ' , '10ᵗʰ'),
    )

    classname = models.CharField(max_length=30 , choices=CLASSNAME_CHOICES , verbose_name = "CLASS")

    contact = models.CharField(max_length=30 , verbose_name = "CONTACT")
    email = models.EmailField(null = True , verbose_name = "EMAIL")

    def __str__(self):
        return self.name


class Fee(models.Model):
    student = models.OneToOneField(Student , on_delete = models.CASCADE, unique=True)
    total_fee = models.CharField(max_length=30 , null = True)
    fees_paid = models.CharField(max_length=30 , null = True)
    fees_due = models.CharField(max_length=30 , null = True)

    books_fee =  models.CharField(max_length=30 , null=True)

    BOOKS_CHOICES = (
        ('Paid', 'Paid'),
        ('Not Paid', 'Not Paid'),
    )
    books_paid = models.CharField(max_length=10, choices=BOOKS_CHOICES , null = True)

    paid_date = models.DateField(null = True)

    def __str__(self):
        return self.student.name





class Teacher(models.Model):
    firstname = models.CharField(max_length=30 , verbose_name = "FIRST NAME")
    lastname = models.CharField(max_length=30 , verbose_name = "LAST NAME")


    GENDER_CHOICES = (
        ('Male', 'Male'),
        ('Female', 'Female'),
    )
    gender = models.CharField(max_length=6, choices=GENDER_CHOICES , verbose_name = "GENDER")

    age = models.PositiveIntegerField(verbose_name = "AGE")

    SUBJECT_CHOICES = (
        ('Mathematics', 'Mathematics'),
        ('Telugu', 'Telugu'),
        ('English', 'English'),
        ('Hindi', 'Hindi'),
        ('Science', 'Science'),
        ('Social', 'Social'),
    )
    subject = models.CharField(max_length=15 , choices=SUBJECT_CHOICES , verbose_name = "SUBJECT")

    email = models.EmailField(max_length=40 , verbose_name = "EMAIL")
    contact = models.CharField(max_length=30 , verbose_name = "CONTACT")
    address = models.CharField(max_length=400 , verbose_name = "ADDRESS")

    def __str__(self):
        return self.firstname





class Id_card(models.Model):
    studentname = models.CharField(max_length=1000 ,  verbose_name = "Student Full Name")
    reg_no = models.PositiveIntegerField( verbose_name = "Registration Number")
    fathername = models.CharField(max_length=1000 ,  verbose_name = "Father Name")
    dob = models.DateField( verbose_name = "Date Of Birth")

    CLASSNAME_CHOICES =(
         ('Nursery' , 'Nursery'),
         ('L.K.G' , 'L.K.G'),
         ('U.K.G' , 'U.K.G'),
         ('1ˢᵗ' , '1ˢᵗ'),
         ('2ⁿᵈ' , '2ⁿᵈ'),
         ('3ʳᵈ' , '3ʳᵈ'),
         ('4ᵗʰ' , '4ᵗʰ'),
         ('5ᵗʰ' , '5ᵗʰ'),
         ('6ᵗʰ' , '6ᵗʰ'),
         ('7ᵗʰ' , '7ᵗʰ'),
         ('8ᵗʰ' , '8ᵗʰ'),
         ('9ᵗʰ' , '9ᵗʰ'),
         ('10ᵗʰ' , '10ᵗʰ'),
    )

    classname = models.CharField(max_length=30 , choices=CLASSNAME_CHOICES ,  verbose_name = "Class")

    BLOODGROUP_CHOICES =(
         ('A+' , 'A+'),
         ('A-' , 'A-'),
         ('B+' , 'B+'),
         ('B-' , 'B-'),
         ('O+' , 'O+'),
         ('O-' , 'O-'),
         ('AB+' , 'AB+'),
         ('AB-' , 'AB-'),

    )

    bloodgroup = models.CharField(max_length=30 , choices=BLOODGROUP_CHOICES ,  verbose_name = "Blood Group")

    resident_add = models.CharField(max_length=2000 ,  verbose_name = "Residential Address")

    permanent_add = models.CharField(max_length=2000 ,  verbose_name = "Permanent Address")

    image = models.ImageField(upload_to ='media/' , null = True ,  verbose_name = "Student Photo Id")

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url



    def __str__(self):
        return self.studentname

schoolmanagement - Copy/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
	<title>School Management</title>

	<meta name="viewport" content="width=device-width, initial-scale=1.0">


	<link rel="stylesheet" href="{% static "stylesheets/global.css" %}" <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

	<link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">

	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css">

	<link rel="stylesheet" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap4.min.css">

	<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
	<script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
	<script src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap4.min.js"></script>

	<style media="screen">
		#id_studentname {
			text-transform: uppercase;
		}




		.index {
			position: relative;
			top: 130px;
			padding: 80px;
		}

		.index a {
			border-radius: 30px;
		}

		.flip-card {
			background-color: transparent;
			width: 300px;
			height: 300px;
			perspective: 1000px;

		}

		.flip-card-inner {
			position: relative;
			width: 100%;
			height: 100%;
			text-align: center;
			transition: transform 0.8s;
			transform-style: preserve-3d;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);

		}

		.flip-card:hover .flip-card-inner {
			transform: rotateY(180deg);
		}

		.flip-card-front,
		.flip-card-back {
			position: absolute;
			width: 100%;
			height: 120%;
			-webkit-backface-visibility: hidden;
			backface-visibility: hidden;
			border-radius: 20px;
			box-shadow: 1px 1px 2px 2px grey;
		}

		.flip-card-front {
			background-color: black;
			color: white;
		}

		.flip-card-back {
			background-color: black;
			color: white;
			transform: rotateY(180deg);
		}



		.id-card {
			background-color: transparent;
			width: 300px;
			height: 380px;
			perspective: 1000px;

		}

		.id-card-inner {
			position: relative;
			width: 100%;
			height: 100%;
			text-align: center;
			transition: transform 0.8s;
			transform-style: preserve-3d;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);

		}


		.id-card-front {
			position: absolute;
			top: 10px;
			width: 100%;
			height: 120%;
			-webkit-backface-visibility: hidden;
			backface-visibility: hidden;
			border-radius: 20px;

		}

		.id-card-front {
			background-repeat: no-repeat;
			background-position: center;
			background-size: cover;
		}

		.top-image {
			position: relative;
			width: 140px;
			height: 140px;
			border-radius: 70px;
			top: 37px;
		}

		.vertical-scrollable>.row {
			position: absolute;
			top: 120px;
			bottom: 100px;
			left: 180px;
			width: 40%;
			overflow-y: scroll;
		}

		.col-sm-8 {
			color: white;
			font-size: 24px;
			padding-bottom: 20px;
			padding-top: 18px;
		}

		.col-sm-8:nth-child(2n+1) {
			background: green;
		}

		.col-sm-8:nth-child(2n+2) {
			background: black;
		}

		#div_id_classname label {}

		#id_classname {}
	</style>



</head>

<body class="img-fluid base-image" style="background-image:linear-gradient(rgba(0, 0, 0, 0.9),rgba(0, 0, 0, 0.9)),url('{% static "images/index7.jpg" %}')">




	<nav class="navbar navbar-expand-sm sticky-top navbar-light bg-light">
		<div class="container">
			<a class="navbar-brand" href="/">My School</a>
			<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar1">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbar1">
				<ul class="navbar-nav">
					<li class="nav-item active">
						<a class="nav-link" href="#">Link</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#">Link</a>
					</li>
				</ul>
				<ul class="navbar-nav ml-auto">
					<li class="nav-item active">
						<a class="nav-link" href="/ad/logout">Logout</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>




	<div class="container-fluid">
		{% block content %}


		{% endblock content %}
	</div>







	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>

	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>

	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>




</body>

</html>

schoolmanagement - Copy/templates/contact.html
{% extends 'base.html' %}
{% load static %}

<html>


<body>
    {% block content %}

    <div class="row p-5 m-4" style="width:100%;,height:100%;">
        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-4">
            <div class="flip-card">
                <div class="flip-card-inner">
                    <div class="flip-card-front">
                        <img src="{% static "images/265674.png" %}" alt="Avatar" style="width:300px;height:300px;">
                        <h3 style="padding-top:5%;font-family: Georgia,'Times New Roman', Times, serif;;">VICE-PRINCIPAL</h3>
                    </div>
                    <div class="flip-card-back">

                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-4">
            <div class="flip-card">
                <div class="flip-card-inner">
                    <div class="flip-card-front">
                        <img src="{% static "images/265674.png" %}" alt="Avatar" style="width:300px;height:300px;">

                        <h3 style="padding-top:5%;font-family: Georgia,'Times New Roman', Times, serif;;">PRINCIPAL</h3>
                    </div>
                    <div class="flip-card-back">
                        <div class="row">
                            <div class="col-12">
                                <br><br>
                                <h3 id="name">Lorem epsum</h3><br><br>
                            </div>
                            <div class="col-5">
                                <h6 id="name">Contact</h6><br>
                                <h6>Email</h6>
                            </div>
                            <div class="col-7">
                                <h6>+91986483638</h6><br>
                                <h6>Lorem@gmail.com</h6>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-4 pt-4">
            <div class="flip-card">
                <div class="flip-card-inner">
                    <div class="flip-card-front">
                        <img src="{% static "images/265674.png" %}" alt="Avatar" style="width:300px;height:300px;">
                    </div>
                    <div class="flip-card-back">

                    </div>
                </div>
            </div>
        </div>
    </div>


    {% endblock content %}
</body>

</html>

schoolmanagement - Copy/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <title>School Management</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <link rel="stylesheet" href="{% static "stylesheets/global.css" %}" <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css">

    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap4.min.css">

    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.25/js/dataTables.bootstrap4.min.js"></script>

    <style media="screen">
        .index-background {
            background-repeat: no-repeat;
            height: 100vh;
            -webkit-background-size: cover;
            background-position: auto;
            background-size: cover;
        }

        .banner-text {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            text-align: center;
        }

        .banner-text p {
            font-family: poppins;
            color: #fff;
        }



        .btn {
            width: 200px;
            border-radius: 10px;
            padding: 10px;
            margin: 20px;
        }

        .text-area {

            font-size: 35px;
            font-family: roboto;
            text-transform: uppercase;
            font-weight: bold
        }

        .text-area span {
            color: yellow;
            opacity: 1;
            transform: translateX(-10px), rotate(360deg), scale(0);
            animation: animate 5s forwards;
        }

        .text-area span {
            display: inline-block;
        }

        .text-area span:nth-of-type(2) {
            animation-delay: .1s;
        }

        .text-area span:nth-of-type(3) {
            animation-delay: .2s;
        }

        .text-area span:nth-of-type(4) {
            animation-delay: .3s;
        }

        .text-area span:nth-of-type(5) {
            animation-delay: .4s;
        }

        .text-area span:nth-of-type(6) {
            animation-delay: .5s;
        }

        .text-area span:nth-of-type(7) {
            animation-delay: .6s;
        }

        .text-area span:nth-of-type(8) {
            animation-delay: .7s;
        }

        @keyframes animate {
            30% {
                transform: translate(0, -50px) rotate(360deg) scale(1);
            }

            60% {
                transform: translate(0, 20px) rotate(360deg) scale(.8);
            }

            100% {
                transform: translate(0) rotate(0deg) scale(1);
            }
        }

        @media (max-width:900px) {
            .banner-text p {
                padding-top: 10px;
            }

            .text-area {
                font-size: 32px;
            }


        }

        @media (min-width:901px) {

            a.nav-link::before {
                content: "Logout";
                color: white;
            }

        }



        .btn-rec:hover::after {
            content: "Coming soon";
            color: white;
        }
    </style>


</head>

<nav class="navbar navbar-expand-sm sticky-top navbar-dark">
    <div class="container">
        <a class="navbar-brand" href="/"><i style="color:green;" class="fa fa-user fa-lg" aria-hidden="true"></i> &nbsp; <span style="font-size:15px;">{{user.username}}</span> </a>

        <div class="" id="navbar1">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/ad/logout"><i style="color:red;position:relative;left:5px;" class="fa fa-power-off fa-lg" aria-hidden="true"></i></a>
                </li>
            </ul>
        </div>
    </div>
</nav>


<body class="index-background image-fluid" style="background-image:linear-gradient(rgba(0, 0, 0, 0.9),rgba(0, 0, 0, 0.9)),url('{% static "images/index7.jpg" %}')">


    <div class="container">

        <div class="banner-text">
            <div class="text-area">
                <span>M</span>
                <span>Y</span><br>
                <span>S</span>
                <span>C</span>
                <span>H</span>
                <span>O</span>
                <span>O</span>
                <span>L</span>


            </div>

            <br><br>

            <p>
                <a class="btn btn-outline-warning" href="/ad/newteacher/">STAFF</a>
                <a class="btn btn-outline-warning" href="/ad/newadm/">STUDENTS</a>
                <a class="btn btn-outline-warning" href="/ad/id_generator/">ID-CARD</a>
                <a class="btn btn-outline-warning" href="/ad/newfee/">FEE</a>
                <a class="btn btn-outline-warning btn-rec">Receipts</a>

            </p>
        </div>
    </div>

    <div class="col-lg-12 com-sm-8" style="background:red; padding: 10px; margin: auto ; width:300px; color:#fff; text-align:center;" id="message">
        Thank you for testing <strong>{{user.username}}</strong>
    </div>

    <script type="text/javascript">
        $(function() {
            setTimeout(function() {
                $("#message").fadeOut(1500);
            }, 500)

        })
    </script>

</body>

</html>